name: Generar lista de mÃºsica

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecutar todos los dÃ­as a las 00:00 UTC
  push:
    paths:
      - '**.m4a'
      - '**.mp3'
      - '.github/workflows/generate_song_list.yml'
      - 'generate_song_list.py'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout del repositorio
        uses: actions/checkout@v3

      - name: ğŸ”§ Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Instalar dependencias
        run: pip install mutagen

      - name: ğŸ§  Ejecutar script para generar JSON
        run: python generate_song_list.py

      - name: ğŸ’¾ Commit y push del JSON actualizado
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git pull origin main --rebase
          git add song_list005.json
          git commit -m 'ğŸ”„ Actualizar song_list005.json automÃ¡ticamente'
          git push
